services:
  db:
    image: postgres:17.6
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devsecret
      POSTGRES_DB: procurementdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  wildfly:
    # Wir ziehen das MultiArch-Image von quai.io (im docker-hub gibt es das nicht)
    image: quay.io/wildfly/wildfly:37.0.1.Final-jdk21
    container_name: wildfly
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # Management User für das lokale WildFly Management Interface (Port 9990)
      WILDFLY_MANAGEMENT_USER: admin
      WILDFLY_MANAGEMENT_PASSWORD: admin123!

      # DB Connection für die lokale Postgres
      DB_URL: jdbc:postgresql://db:5432/procurementdb
      DB_USER: devuser
      DB_PASSWORD: devsecret
    ports:
      - "8080:8080"   # App
      - "9990:9990"   # Management
    volumes:
      - ./docker/deployments:/opt/jboss/wildfly/standalone/deployments
      - ./docker/wildfly-init.sh:/opt/jboss/wildfly-init.sh
      - ./docker/configure-datasource.cli:/opt/jboss/wildfly/configure-datasource.cli
      - ./docker/modules/org/postgresql/main:/opt/jboss/wildfly/modules/system/layers/base/org/postgresql/main

    command: ["/bin/bash", "/opt/jboss/wildfly-init.sh"]
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge